name: clinician_mobile
description: Aura Clinical Clinician Mobile Application for on-the-go alerts & schedules
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  aura_core:
    path: ../../packages/core
  aura_design_system:
    path: ../../packages/design_system

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
