name: patient_mobile
description: DOCAAS Clinical Patient Mobile Application for iOS & Android
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  aura_core:
    path: ../../packages/core
  docaas_design_system:
    path: ../../packages/design_system
  aura_clinical:
    path: ../../packages/clinical
  aura_appointments:
    path: ../../packages/appointments
  docaas_networking:
    path: ../../packages/networking

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
